### ISSUE TITLE
Inkompatible TouchEvent library

### ISSUE THREAD

**Issue by AshmodaiVirolac** [GerLech/ArduiTouchSmart#1]
Einige der Funktionen, die von der Klasse TouchEvent angesprochen werden (z.B. autocalibrate, getMinMax, registerOnAllEvents) existieren in der auf Github veröffentlichten TouchEvent library nicht

**Comment by GerLech** [comment]
Danke für den Hinweis!
Ich habe vergessen die neueste Version auf Github zu posten. Das ist nun geschehen.

**Comment by GerLech** [comment]
Done
