### ISSUE TITLE
How to get access to Buttons and Sliders states

### ISSUE THREAD

**Issue by sputnik1984** [GerLech/ArduiTouchSmart#3]
Dear Mr. Lechner,

thank you for the work with the Sliders and Buttons and all the other stuff. I baught your book and my intention was to learn how to deal with the Tochdisplay for my own projects. Now, i have the problem that i cant get direct access to the actual state of one of three buttons for example. How can i do that if i dont want to use MQTT? Is there an easy example how to switch 3 different LED´s with three Bool-Buttons directly on the same ESP-Chip where the TFT-Display is connected? This would be helpfull for me to understand how to use the  ATS-Library for other Projects.
In my own example i get a touch event and the koordinates over serial but not the actual state or the button index. 
Thank you very much.

Conrad

**Comment by GerLech** [comment]
Hi Conrad

the simplest way with only minimal changes is to use the bool onPublish(const char * topic, const char * message) callback function. This function will be called, whenever a button swich or slider has changed. Normally this function is used to send commands to the MQTT broker, but you can also use it for immediate actions. The argument topic let you identify wich widget has changed. The argument message contains for buttons and switches the state "ON" or "OFF". For sliders the message contains the value as a string. I hope this helps.

**Comment by sputnik1984** [comment]
Dear Mr. Lechner,
excuse me - i did some research about your message in your librarys. I found allways the Funktion "registerOnPublish". The onPublish funktion you mentioned is only inside the ArduiTouchSmart.h as private published. I made it public but that didn´t help me. I also look how the MQTT part handles the touch request, but with no luck. Can you please give me a second hint how to solve my problem? I think you made this very good library - and it could be used even more felxible for other tasks if we get more basic examples.

Best regards.
Conrad
